# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#  desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end
desc "run tests"
lane :executetest do
begin
            # Something where you'd like to be able to react to failures

   scan(
    scheme: "iOSProjectTests",
    devices: ["iPhone X"],
    output_style: "standard")
            # If ANY exception happens, let me handle it
            rescue => ex
            # re-raise the exception unless it's something we're OK with ignoring
            # raise ex unless ex.message.include?('Error message of interest')
            # UI.error ex
            # UI.user_error!("Lint check or Test case failed, but continuing anyway!")
        UI.important("There were a few failing test cases. Continuing execution")

        end
end